export const fakeTransactions = [
  // Enero
  {
    date: '2025-01-03',
    description: 'NEQUI Top-Up',
    amount: 120000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-01-04',
    description: 'Exito Groceries',
    amount: -38000,
    type: 'expense',
    category: 'groceries',
  },
  {
    date: '2025-01-05',
    description: 'Netflix Subscription',
    amount: -16000,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-01-06',
    description: 'Uber Ride',
    amount: -12000,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-01-08',
    description: 'Lunch at El Corral',
    amount: -20000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-01-10',
    description: 'Transfer to MAMÁ',
    amount: -50000,
    type: 'transfer',
    category: 'personal_transfer',
  },

  // Febrero
  {
    date: '2025-02-01',
    description: 'NEQUI Top-Up',
    amount: 100000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-02-03',
    description: 'Carulla Market',
    amount: -45000,
    type: 'expense',
    category: 'groceries',
  },
  {
    date: '2025-02-06',
    description: 'Spotify',
    amount: -14900,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-02-07',
    description: 'Uber Ride',
    amount: -9000,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-02-08',
    description: 'Dinner at WOK',
    amount: -35000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-02-14',
    description: 'Transfer to NOVIA',
    amount: -30000,
    type: 'transfer',
    category: 'personal_transfer',
  },

  // Marzo
  {
    date: '2025-03-01',
    description: 'NEQUI Top-Up',
    amount: 110000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-03-02',
    description: 'Farmatodo',
    amount: -20000,
    type: 'expense',
    category: 'health',
  },
  {
    date: '2025-03-05',
    description: 'Netflix',
    amount: -16000,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-03-06',
    description: 'Uber Ride',
    amount: -10500,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-03-07',
    description: 'Dinner at Crepes & Waffles',
    amount: -32000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-03-15',
    description: 'Transfer to HERMANO',
    amount: -25000,
    type: 'transfer',
    category: 'personal_transfer',
  },

  // Abril
  {
    date: '2025-04-02',
    description: 'NEQUI Top-Up',
    amount: 90000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-04-04',
    description: 'D1 Groceries',
    amount: -28000,
    type: 'expense',
    category: 'groceries',
  },
  {
    date: '2025-04-06',
    description: 'Spotify',
    amount: -14900,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-04-07',
    description: 'Uber Ride',
    amount: -8800,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-04-08',
    description: 'Burger King',
    amount: -22000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-04-20',
    description: 'Transfer to PAPÁ',
    amount: -45000,
    type: 'transfer',
    category: 'personal_transfer',
  },

  // Mayo (ya tienes algunos, los conservo y complemento)
  {
    date: '2025-05-01',
    description: 'NEQUI Top-Up',
    amount: 100000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-05-02',
    description: 'Payment at LA SUPERIOR JBG',
    amount: -32000,
    type: 'expense',
    category: 'groceries',
  },
  {
    date: '2025-05-03',
    description: 'Transfer to ANA PEREZ',
    amount: -25000,
    type: 'transfer',
    category: 'personal_transfer',
  },
  {
    date: '2025-05-04',
    description: 'UBER Ride',
    amount: -18000,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-05-05',
    description: 'Spotify Subscription',
    amount: -14000,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-05-06',
    description: 'NEQUI Top-Up',
    amount: 120000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-05-07',
    description: 'AIRBNB Booking',
    amount: -80000,
    type: 'expense',
    category: 'travel',
  },
  {
    date: '2025-05-08',
    description: 'Lunch at BURGER PARK',
    amount: -22000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-05-09',
    description: 'NEQUI Top-Up',
    amount: 95000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-05-10',
    description: 'Transfer to JUAN GONZALEZ',
    amount: -30000,
    type: 'transfer',
    category: 'personal_transfer',
  },

  // Junio
  {
    date: '2025-06-01',
    description: 'NEQUI Top-Up',
    amount: 105000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-06-03',
    description: 'Domicilios.com',
    amount: -27000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-06-04',
    description: 'Uber',
    amount: -11000,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-06-06',
    description: 'Netflix',
    amount: -16000,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-06-10',
    description: 'Exito Groceries',
    amount: -35000,
    type: 'expense',
    category: 'groceries',
  },
  {
    date: '2025-06-14',
    description: 'Transfer to HERMANA',
    amount: -40000,
    type: 'transfer',
    category: 'personal_transfer',
  },

  // Julio
  {
    date: '2025-07-01',
    description: 'NEQUI Top-Up',
    amount: 130000,
    type: 'income',
    category: 'recarga',
  },
  {
    date: '2025-07-03',
    description: 'Falabella Purchase',
    amount: -75000,
    type: 'expense',
    category: 'shopping',
  },
  {
    date: '2025-07-05',
    description: 'Spotify',
    amount: -14900,
    type: 'expense',
    category: 'subscriptions',
  },
  {
    date: '2025-07-06',
    description: 'Uber Ride',
    amount: -12000,
    type: 'expense',
    category: 'transport',
  },
  {
    date: '2025-07-10',
    description: 'Lunch at Subway',
    amount: -18000,
    type: 'expense',
    category: 'restaurants',
  },
  {
    date: '2025-07-12',
    description: 'Transfer to NOVIA',
    amount: -35000,
    type: 'transfer',
    category: 'personal_transfer',
  },
];
